import random

#UTILIZAMOS O RANDOM QUANDO QUEREMOS ESCOLHER ALEATORIAMENTE  UMA INFORMAÇÃO

resultado = random.random() *10

#GERA UM NUMERO ALEATÓRIO ENTRE 0 E 1, QUNADO MULTIPLICAMOS POR 10, GERA UM NUMEOR ALEATÓRIO DE 0 - 10