
while True:
  print("-------Menu-------")
  print("1- CADASTRO DE CURSO:")
  print("2- CADASTRO DE ALUNOS:")
  print("3- Sair")
  opcao = int(input("Escolha uma opção:"))
  if opcao == 1:
        nomecurso = input("Informe o nome do curso:")
        professor = input("Informe o nome do professor:")
        print("Cadastro concluído!")
  elif opcao == 2:
  
        nomealuno = input("Informe o nome do Aluno:")
        rgaluno = input("Informe o RG do Aluno:")
        print("Cadastro concluído!")

  elif opcao == 3:
       print("Saindo.")
       break
  
  else:
       print("Opção inválida, tente novamente.")

       4161
