'''
DEFINA UMA LISTA COM 6 ITENS QUE TENHAM PELO MENOS 3 CLASSES DIFERTENTES E UTILIZE PRINT PARA EXIBIR O TERCEIRO ELEMENTO DA LISTA
'''

lista_ex = [True, 2.5,'Mardel',56, False]

print(lista_ex[2])


